apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ngi-demo
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels: 
        name: nginx
    spec:
      containers:
        - image: nginx
          name: spc
          ports:
            - containerPort: 80
              protocol: TCP